from sum.sum import sum




# why first test failed  but the second passed

def test_sum1():
    assert sum(-6, 2) == 10




def test_sum3():
    assert sum(3, 2) == 5